site_name: CSnakes
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Reference: reference.md
  - Environment and Package Management: environments.md
  - Asynchronous Functions: async_support.md
  - Buffer Protocol and NumPy Arrays: buffers.md
  - Advanced Usage: advanced.md
  - Limitations: limitations.md
  - FAQ: faq.md
  - Examples: examples.md

theme:
  name: material
  features:
    - content.code.copy
repo_url: https://github.com/tonybaloney/csnakes
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - admonition
  - pymdownx.details
