site_name: CSnakes
nav:
  - Home: index.md
  - Getting Started:
    - Quick Start: getting-started/quick-start.md
    - Installation: getting-started/installation.md
    - First Example: getting-started/first-example.md
    - Templates: getting-started/templates.md
  - User Guide:
    - Basic Usage: user-guide/basic-usage.md
    - Type System: user-guide/type-system.md
    - Environment Management: user-guide/environments.md
    - Exception Handling: user-guide/errors.md
    - Buffers & NumPy: user-guide/buffers.md
    - Async Functions: user-guide/async.md
    - Deployment in Containers: user-guide/deployment.md
  - Examples & Showcase:
    - Sample Projects: examples/sample-projects.md
    - Projects Using CSnakes: examples/projects-using-csnakes.md
  - Advanced Topics:
    - Overview: advanced/advanced-usage.md
    - Large Integers: advanced/big-integers.md
    - Free-Threading: advanced/free-threading.md
    - Generators: advanced/generators.md
    - Manual Integration: advanced/manual-integration.md
    - Hot Reload: advanced/hot-reload.md
    - Signal Handlers: advanced/signal-handlers.md
    - Native AOT: advanced/native-aot.md
    - Performance Optimization: advanced/performance.md
    - Troubleshooting: advanced/troubleshooting.md
  - Community:
    - FAQ: community/faq.md
    - Limitations: community/limitations.md
    - Roadmap: community/roadmap.md
    - Contributing: community/contributing.md

theme:
  name: material
  logo: res/icon_white.png
  favicon: res/icon_black.png
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    - scheme: default  # Light Mode
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-2
        name: Switch to dark mode
    - scheme: slate # Dark Mode
      primary: deep purple
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
repo_url: https://github.com/tonybaloney/csnakes
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - admonition
  - pymdownx.details
